// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtU-KU8RSWA4RAPMLcRT2C4OH7LmXE98',
    appId: '1:807020993399:web:9debf36ad50c78ecb5df72',
    messagingSenderId: '807020993399',
    projectId: 'app-seguimiento-e60a2',
    authDomain: 'app-seguimiento-e60a2.firebaseapp.com',
    storageBucket: 'app-seguimiento-e60a2.appspot.com',
    measurementId: 'G-EW7NR43FGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgugCO6glQ6sgn5Of0kxI0AqBqRpaj9GM',
    appId: '1:807020993399:android:fe50b03049fa4332b5df72',
    messagingSenderId: '807020993399',
    projectId: 'app-seguimiento-e60a2',
    storageBucket: 'app-seguimiento-e60a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoABqbc_55YbCmrzWNjnWks8ei5L5NJtM',
    appId: '1:807020993399:ios:03eebed281bf98bcb5df72',
    messagingSenderId: '807020993399',
    projectId: 'app-seguimiento-e60a2',
    storageBucket: 'app-seguimiento-e60a2.appspot.com',
    iosClientId: '807020993399-t29dpi7296kvm6cedcgqs2jkh2663adl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSeguimiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoABqbc_55YbCmrzWNjnWks8ei5L5NJtM',
    appId: '1:807020993399:ios:03eebed281bf98bcb5df72',
    messagingSenderId: '807020993399',
    projectId: 'app-seguimiento-e60a2',
    storageBucket: 'app-seguimiento-e60a2.appspot.com',
    iosClientId: '807020993399-t29dpi7296kvm6cedcgqs2jkh2663adl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSeguimiento',
  );
}
